#!/bin/bash
# Workaround: Codium snap injects old GTK/glibc paths into env.
# Unset them so system libs are used instead.
unset GTK_PATH GIO_MODULE_DIR GTK_EXE_PREFIX GSETTINGS_SCHEMA_DIR \
      LOCPATH GTK_IM_MODULE_FILE GDK_BACKEND GTK_MODULES \
      XDG_DATA_DIRS \
      GTK_EXE_PREFIX_VSCODE_SNAP_ORIG GTK_PATH_VSCODE_SNAP_ORIG \
      GIO_MODULE_DIR_VSCODE_SNAP_ORIG GTK_IM_MODULE_FILE_VSCODE_SNAP_ORIG \
      GDK_BACKEND_VSCODE_SNAP_ORIG XDG_DATA_DIRS_VSCODE_SNAP_ORIG
exec pnpm tauri dev
